# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'admin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Administration(object):
    def setupUi(self, Administration):
        Administration.setObjectName("Administration")
        Administration.resize(400, 300)
        self.pushButton = QtWidgets.QPushButton(Administration)
        self.pushButton.setGeometry(QtCore.QRect(10, 40, 121, 31))
        self.pushButton.setObjectName("pushButton")
        self.listView = QtWidgets.QListView(Administration)
        self.listView.setGeometry(QtCore.QRect(140, 10, 256, 271))
        self.listView.setObjectName("listView")
        self.pushButton_2 = QtWidgets.QPushButton(Administration)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 90, 121, 31))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(Administration)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 140, 121, 31))
        self.pushButton_3.setObjectName("pushButton_3")

        self.retranslateUi(Administration)
        QtCore.QMetaObject.connectSlotsByName(Administration)

    def retranslateUi(self, Administration):
        _translate = QtCore.QCoreApplication.translate
        Administration.setWindowTitle(_translate("Administration", "Dialog"))
        self.pushButton.setText(_translate("Administration", "список клиентов"))
        self.pushButton_2.setText(_translate("Administration", "статистика клиентов"))
        self.pushButton_3.setText(_translate("Administration", "настройки сервера"))
